name: Netlify

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn
      - run: yarn gulp build
      - run: npm install
      - run: npm netlify-cli deploy --dir=./public
        env:
          NETLIFY_AUTH_TOKEN: 'd732f8a2e2354edfd844c0e681d6fbb22b6a85606626b58f481d98cd1c5a6c57'
          NETLIFY_SITE_ID: '3f3b19d6-3a30-4ad2-841d-7b697730aaf9'
